import os 
import scons_compiledb

env = Environment(CPPPATH = [".", "../inc/","../src/"])
scons_compiledb.enable(env)

env.Program("alarm_mutex", 
["./3_2_2_Locking_and_unlocking_mutex/alarm_mutex.c"])
env.Program("cond_static", 
["./3_3_1_creating_and_destroying_a_cond/cond_static.c"])
env.Program("cond_dynamic",
["./3_3_1_creating_and_destroying_a_cond/cond_dynamic.c"])
env.Program("cond",
["./3_3_2_waiting_on_a_cond_var/cond.c"])
env.Program("alarm_cond",
["./3_3_4_alarm_with_cond_var/alarm_cond.c"])


env.CompileDb()

